# Generated by Django 4.0.5 on 2022-06-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriplans_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
