# Generated by Django 4.0.5 on 2022-06-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriplans_app', '0003_alter_patients_email_alter_patients_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='email',
            field=models.EmailField(default='0', max_length=254),
        ),
    ]
