# Generated by Django 4.0.5 on 2022-06-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriplans_app', '0004_alter_patients_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='current_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patients',
            name='target_weight',
            field=models.IntegerField(default=0),
        ),
    ]
