# Generated by Django 4.0.5 on 2022-06-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriplans_app', '0006_alter_patients_gender_alter_patients_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='email',
            field=models.EmailField(default='0', max_length=254, unique=True),
        ),
    ]
