# Generated by Django 4.0.5 on 2022-06-28 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutriplans_app', '0007_alter_patients_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Μeasurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=100)),
                ('weight', models.FloatField(default=0.0)),
                ('fat', models.FloatField(default=0.0)),
                ('muscle_mass', models.FloatField(default=0.0)),
                ('bone_mass', models.FloatField(default=0.0)),
                ('liquids', models.FloatField(default=0.0)),
                ('vinceral_fat', models.FloatField(default=0.0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutriplans_app.patients')),
            ],
        ),
    ]
