# Generated by Django 4.0.5 on 2022-07-01 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutriplans_app', '0009_alter_patients_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Μeasurements',
            new_name='Measurements',
        ),
    ]
