# Generated by Django 4.0.5 on 2022-07-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriplans_app', '0010_rename_μeasurements_measurements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
