# Generated by Django 4.0.5 on 2022-07-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriplans_app', '0012_alter_patients_current_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='current_weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
