# Generated by Django 4.0.5 on 2022-07-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriplans_app', '0013_alter_patients_current_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='current_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
