# Generated by Django 4.0.5 on 2022-07-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriplans_app', '0014_alter_patients_current_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='current_weight',
        ),
        migrations.AddField(
            model_name='measurements',
            name='activity_factor',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='patients',
            name='name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='patients',
            name='target_weight',
            field=models.IntegerField(default=0.0),
        ),
    ]
