# Generated by Django 4.0.5 on 2022-07-09 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutriplans_app', '0016_equivalents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equivalents',
            old_name='patient',
            new_name='client',
        ),
    ]
