# Generated by Django 4.0.5 on 2022-07-09 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutriplans_app', '0017_rename_patient_equivalents_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equivalents',
            old_name='target_Calories',
            new_name='target_calories',
        ),
    ]
