# Generated by Django 4.0.5 on 2022-07-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriplans_app', '0019_rename_patients_clients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='initial_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clients',
            name='notes',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
